const fs = require('fs');
const html = fs.readFileSync('story.txt', 'utf8');
const main = html.indexOf('<main');
const mainEnd = html.indexOf('</main>');
const postContainer = html.indexOf('<article');
const postContainerEnd = html.indexOf('</article>');
const comments = html.indexOf('<section class="comments-section"');
const commentsEnd = html.indexOf('</section>');
console.log("main:", main, "->", mainEnd);
console.log("article:", postContainer, "->", postContainerEnd);
console.log("comments:", comments, "->", commentsEnd);
